gui_files = [
	'bookentry.cc',
	'dialogentry.cc',
	'downloadqueue.cc',
	'eggtrayicon.c',
	'favoritehubs.cc',
	'finishedtransfers.cc',
	'hashdialog.cc',
	'hub.cc',
	'mainwindow.cc',
	'prefix.cc',
	'privatemessage.cc',
	'publichubs.cc',
	'search.cc',
	'settingsdialog.cc',
	'settingsmanager.cc',
	'sharebrowser.cc',
	'treeview.cc',
	'wulfor.cc',
	'wulformanager.cc',
	'WulforUtil.cc']

Import('env')

# Get the cflags. We copy the env since so we don't want to add these flags globally.
env_gui = env.Copy()
env_gui.ParseConfig('pkg-config --cflags libglade-2.0')
env_gui.ParseConfig('pkg-config --cflags gthread-2.0')

# Build the gui_files
guiObjs = env_gui.Object(gui_files)

Return('guiObjs')
