gui_files = [	'selecter.cc',				'wulformanager.cc',
				'bookentry.cc',				'mainwindow.cc',
				'wulfor.cc', 				'prefix.cc',
				'publichubs.cc',			'treeviewfactory.cc',
				'hub.cc',					'privatemessage.cc',
				'sharebrowser.cc']

Import('env')
guiObjs = env.Object(gui_files)
Return('guiObjs')
